apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: quay-operator
spec:
  sourceType: grpc
  image: quay.io/kmullins/quay-operator-catalog@sha256:32e6f4108c555c768be2e6f46258262fd08f56b87fb631580737a9023d1cf087
